
server:
  port: 9000
dubbo:
  application:
    id: consumer
    name: consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
  metadata-report:
    address: zookeeper://127.0.0.1:2181

spring:
  datasource:
    url: jdjdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: