DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
id BIGINT NOT NULL AUTO_INCREMENT,
user_id BIGINT NULL,
user_name VARCHAR ( 255 ) NULL,
PASSWORD VARCHAR ( 255 ) NULL,
nick_name VARCHAR ( 255 ) NULL,
certificate_num VARCHAR ( 255 ) NULL,
create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
operate_user VARCHAR ( 255 ) NULL,
PRIMARY KEY ( id ) USING BTREE 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '用户';

DROP TABLE IF EXISTS goods;
CREATE TABLE goods (
id BIGINT NOT NULL AUTO_INCREMENT,
goods_id BIGINT NULL,
goods_name VARCHAR ( 255 ) COMMENT '商品名称',
goods_type VARCHAR ( 255 ) '商品类型',
weight VARCHAR ( 255 ) '重量',
price VARCHAR ( 255 ) '价格',
create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP '创建时间',
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP '更新时间',
PRIMARY KEY ( id ) USING BTREE 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '商品';

DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
order_id BIGINT NOT NULL AUTO_INCREMENT,
user_id BIGINT COMMENT '用户编号',
account FLOAT COMMENT '支付金额',
order_state SMALLINT COMMENT '订单状态 1.未支付 2.已支付 3.未发货 4.已发货 5.交易成功 6.交易关闭',
pay_type INT COMMENT '支付类型：1.在线支付 2.货到付款',
create_time TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP COMMENT '更新时间',
PRIMARY KEY ( order_id ) USING BTREE 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '订单';

DROP TABLE IF EXISTS order_detail;
CREATE TABLE order_detail (
id BIGINT NOT NULL AUTO_INCREMENT,
goods_id BIGINT COMMENT '商品编号',
order_id BIGINT COMMENT '订单编号',
num INT COMMENT '数量',
price FLOAT COMMENT '价格',
goods_name VARCHAR ( 255 ) COMMENT '商品名称',
create_time TIMESTAMP COMMENT '开始时间',
update_time TIMESTAMP COMMENT '更新时间',
PRIMARY KEY ( id ) USING BTREE 
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '订单详情';