spring:
  shardingsphere:
    datasource:
      names: ds1, ds2
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password:
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3307/shopping?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password:
      sharding:
        tables:
          orders:
            actual-data-nodes: ds1.order_copy$->{1..16}, ds3.order_copy$->{1..16}
            key-generator:
              column: order_id
              type: SNOWFLAKE
            database-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: ds$->{order_id%2==0?1:3}
            table-stragety:
              inline:
                sharding-column: order_id
                algorithm-expression: order_copy$->{order_id%16+1}
      props:
        sql.show: true